### PR TITLE
fix(types): remove `redirect` option

### LINKED ISSUE #611: [BUG]: `redirect` option not passed through
### What happened?

The `redirect` option is still defined in the types as an option that can be passed, however it isn't getting passed along

### Versions

`@octokit/request` v8

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wolfy1339**
Resolves #611 

----

### Before the change?

* The `redirect` option was defined in the types, but wasn't passed through in the options

### After the change?

* The `redirect` option is properly passed through to fetch

### Other information

*

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`

----

### CODE REVIEW

File: src/fetch-wrapper.ts [hunk 1]
```diff
@@ -41,6 +41,7 @@ export default function fetchWrapper(
     body: requestOptions.body,
     headers: requestOptions.headers as HeadersInit,
     signal: requestOptions.request?.signal,
+    redirect: requestOptions.redirect,
```
Comment (gr2m) [inline src/fetch-wrapper.ts:44]: wait where is `redirect` defined? I don't see it in `@octokit/types`?

Comment (wolfy1339) [reply src/fetch-wrapper.ts:44]: It's defined above into he function signature

Comment (gr2m) [reply src/fetch-wrapper.ts:44]: I'm sorry I misunderstood and didn't check 😞 I don't see where we use that option, do you know where it's coming from? I see this commit but not sure before that: https://github.com/octokit/request.js/commit/7b38319b135d6bb52dbc8f9a394856da6e6b70ce

 If anything it should be passed as `requestOptions.request.redirect`, not as `requestOptions.redirect`.

I think we shouldn't pass it through and remove the type, until someone complaints that it broke something. Sorry for the back-and-forth

Comment (wolfy1339) [reply src/fetch-wrapper.ts:44]: It's been defined that way for 4 years now, since the very beginning of the typescript conversion

It was first introduced in https://github.com/octokit/request.js/commit/7fe91b826a86d8d31c1d21aff9ab9180a552614d

Comment (wolfy1339) [reply src/fetch-wrapper.ts:44]: The option itself has been defined that way since v1.2.0
It was first introduced in https://github.com/octokit/request.js/commit/d8c60e52948a59feb8cc0d07cf8adb511ae5d672

Comment (gr2m) [reply src/fetch-wrapper.ts:44]: I'm pretty sure that was due to `node-fetch`'s behavior, you could set `redirect` to `manual` and extract the redirect URL that way. But that's not the behavior of native fetch anyway. I'd say we do not add it back, and remove `redirect` from the types

**Review by gr2m — APPROVED** [review]
