### PR TITLE
fix: use `json-with-bigint` instead of built-in JSON methods in order to properly support int64's

### LINKED ISSUE #797: [BUG]: Loss of integer precision in API responses
### What happened?

In the last few days, I've noticed the webhooks API ([List deliveries for an app webhook](https://docs.github.com/en/rest/apps/webhooks?apiVersion=2022-11-28#list-deliveries-for-an-app-webhook)) has started returning big integers ids. For example, previously I'd get back an id like `199287304442`, now I get back one like `3804004623172239366`.

This is problematic for octokit, since it [does a JSON.parse of the response body](https://github.com/octokit/request.js/blob/9ba6ae0fd2eff35a6c29a9f032eca6e9ba002976/src/fetch-wrapper.ts#L170), which does not natively handle big integers. So in JavaScript the value I get is `3804004623172239400` due to loss of precision. Because these values are wrong, I can't use them for subsequent API calls, e.g. to [redeliver a failed delivery](https://docs.github.com/en/rest/apps/webhooks?apiVersion=2022-11-28#redeliver-a-delivery-for-an-app-webhook).

This can be potentially worked around by manually wiring up requests and JSON processing, but then I can't fully use octokit. I suspect octokit could fix this by adopting something like [json-bigint](https://www.npmjs.com/package/json-bigint), though that would likely have downstream implications.

### Versions

Octokit.js v7.0.6, Node.js v22.21.1

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wolfy1339**
Resolves #797 

----

### Before the change?

* Used `JSON.parse()` and `JSON.stringify()` which cannot handle BigInt

### After the change?

* Use the `json-with-bigint` package

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

----

### CODE REVIEW

File: src/fetch-wrapper.ts [hunk 1]
```diff
@@ -164,12 +164,13 @@ async function getResponseData(response: Response): Promise<any> {
   const mimetype = safeParse(contentType);
 
   if (isJSONResponse(mimetype)) {
-    let text = "";
+    let text = ""
     try {
-      text = await response.text();
-      return JSON.parse(text);
+      text = await request.text();
```
Comment (wolfy1339) [inline src/fetch-wrapper.ts]:
```suggestion
      text = await response.text();
```

File: src/fetch-wrapper.ts [hunk 2]
```diff
@@ -164,12 +164,13 @@ async function getResponseData(response: Response): Promise<any> {
   const mimetype = safeParse(contentType);
 
   if (isJSONResponse(mimetype)) {
-    let text = "";
+    let text = ""
```
Comment (wolfy1339) [inline src/fetch-wrapper.ts]:
```suggestion
    let text = "";
```

File: src/fetch-wrapper.ts [hunk 3]
```diff
@@ -164,12 +164,13 @@ async function getResponseData(response: Response): Promise<any> {
...
     try {
       text = await response.text();
-      return JSON.parse(text);
+      JSON.parse(text);
+      return await response.json();
     } catch (err) {
-      return text;
+      return "";
```
Comment (wolfy1339) [inline src/fetch-wrapper.ts]:
```suggestion
      return text;
```

**Comment by jenseng** [comment]
Unfortunately [json()](https://developer.mozilla.org/en-US/docs/Web/API/Response/json) doesn't support bigint yet either (see https://github.com/whatwg/fetch/issues/104):

```js
new Response('{"id":3804004623172239366}')).json().then(({id}) => console.log(id))
// 3804004623172239400
```

So in the meantime something like [json-bigint](https://www.npmjs.com/package/json-bigint) will probably be needed


_**edit:** json-bigint is just an example, there are other options. it's the most popular, but appears unmaintained. so it would be good to look at other options, e.g. https://github.com/Ivan-Korolenko/json-with-bigint or https://github.com/josdejong/lossless-json_

**Comment by wolfy1339** [comment]
I made the changes necessary, this should in theory work

File: src/fetch-wrapper.ts
Comment (jenseng) [inline src/fetch-wrapper.ts]: what do you think about also changing this line to use JSONStringify? that way bigints in the request body are handled correctly too

**Review by jenseng — APPROVED** [review]
looks great, just one suggestion (though it could come as a separate PR)

**Comment by jenseng** [comment]
also the PR summary needs a tweak since it still says `Uses the .json() method on the response object`

File: src/fetch-wrapper.ts
Comment (wolfy1339) [reply src/fetch-wrapper.ts]: Yeah, that should be doable

**Review by gr2m — APPROVED** [review]
